server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
spring:
  datasource:
    url: jdbc:postgresql://dpg-cksg7305vl2c73erbob0-a/loginfpt
    username: loginfpt_user
    password: Lh7BFgd0kh9vsOfjBkef40D7p5cTPhNb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        id:
          new_generator_mappings: false
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  main:
    allow-circular-references: true
  devtools:
    restart:
      log-condition-evaluation-delta: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: offftrick@gmail.com
    password: bsamnoudhsiqxeoi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



