server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loginfpt?useSSL=false
    username: postgres
    password: Strongpass@
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        id:
          new_generator_mappings: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  main:
    allow-circular-references: true
  devtools:
    restart:
      log-condition-evaluation-delta: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: offftrick@gmail.com
    password: bsamnoudhsiqxeoi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: "@spring.profiles.active@"
google:
  app:
    id: 313910921715-4on84aosmdsj5s7phd0e5l2qq9f0j222.apps.googleusercontent.com
    secret: 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
  redirect:
    uri: http://localhost:8080/login-google
  link:
    get:
      token: https://accounts.google.com/o/oauth2/token
      user_info: https://www.googleapis.com/oauth2/v1/userinfo?access_token=

